### ISSUE TITLE
issue to generate specific address private key?

### ISSUE THREAD

**Issue by TBSMobile** [essentiaone/HDWallet#24]
I have generated a private key for litecoin for the specific derived path "m/44/2/0/0/0". but private key can not generate same as "https://iancoleman.io/bip39". 

different path:
1. m/44/2/0/0/0
2. m/44/2/0/0/1
3. m/44/2/0/0/2 and so on..

Can you please provide a solution to this?

**Comment by impul** [comment]
Hi, @SazzadIproliya, thank you for your question.

Our library provides two ways for generating Litecoin(or Bitcoin, Ethereum and Bitcoin Classic) wallets:

1. Simple way, use account generating
```Swift
let mnemonic = Mnemonic.create()
let seed = Mnemonic.createSeed(mnemonic: mnemonic)
let wallet = Wallet(seed: seed, coin: .litecoin)
let firstAccount = wallet.generateAccount(at: 0) 
let secondAccount = wallet.generateAccount(at: 1) 
```
It equal "m/44'/2'/0'/0/0" and "m/44'/2'/0'/0/1". 
Account have all required fields for creating transaction: private key, public key, address and raw private key.

 2. Second way it is creating HD path manually: 
```Swift
let mnemonic = Mnemonic.create()
let seed = Mnemonic.createSeed(mnemonic: mnemonic)
let privateKey = PrivateKey(seed: seed, coin: . litecoin)
// BIP39 key derivation
// m/44'
let purpose = privateKey.derived(at: .hardened(44))      
// m/44'/2'
let coinType = purpose.derived(at: .hardened(2))
// m/44'/2'/0'
let account = coinType.derived(at: .hardened(0))
// m/44'/2'/0'/0
let change = account.derived(at: .notHardened(0))
// m/44'/2'/0'/0/0
let firstPrivateKey = change.derived(at: .notHardened(0))
```
Now you can get same to first way information:
```Swift
let address = firstPrivateKey.publicKey.address
let privateKey = firstPrivateKey.get()
let publicKey = firstPrivateKey.publicKey.get()
```

These two methods give the same result.
Maybe, you have not specified "Hardened" or "Non-hardened" HD nodes? This functionality is implemented in `DerivationNode` component. 

If something is not clear please ask.

**Comment by TBSMobile** [comment]
Yes, you are true. But my question is that public key and address generate same as "[https://iancoleman.io/bip39](https://iancoleman.io/bip39)".

But private key generated from HDwallet and Coleman website both are different.

**In HD Wallet:**

**Path: m/44'/2'/0'/0/0**
Mainnet ChildKey0:  LXbmmJEuwYrFN21vLGwFkaYz5zeDEDanGv
Mainnet PrivateKey0:  KxeEqrv9ahjE4m5LPcFvznBNnhb1toG7YHP34dr82iFZu9taYuP7
Mainnet PublicKey0:  02ddf59d9deb77616c77c8f4c024e0e5137c92c3ad43dd39ad71c8f1e04574110e

**Path: m/44'/2'/0'/0/1**
Mainnet ChildKey1:  LPfb4Rm9WJNQac1WSFwFLN4FkQGY3wecBy
Mainnet PrivateKey1:  L1mav5PTxHgW2jeZHDZvSHCcPmTP8CDMebNbSPtibatYXeNHG6vm
Mainnet PublicKey1: 026bc2812d146cd2f4aeec2d2a5d1c69bbadc735a3f7ff30ac73587f327eb427d9

**In https://iancoleman.io/bip39**

**Path: m/44'/2'/0'/0/0**  
LXbmmJEuwYrFN21vLGwFkaYz5zeDEDanGv 
02ddf59d9deb77616c77c8f4c024e0e5137c92c3ad43dd39ad71c8f1e04574110e T4UWHcDKz5hpqbiCwFCoD8ikjZEKxtH1MVHHvSUfbgRjR3WR6JFU

**Path: m/44'/2'/0'/0/1** 
LPfb4Rm9WJNQac1WSFwFLN4FkQGY3wecBy 
026bc2812d146cd2f4aeec2d2a5d1c69bbadc735a3f7ff30ac73587f327eb427d9 
T7brMpgeMff6oaHRprWnedjzLd6hCHEFToGrJCXGAZ4i3XvorQMs

But My question is that address and public key generate same but private key generated differently. 

**Implemented Method:**

func testMainnetChildKeyDerivation() {
        let privateKey = PrivateKey(seed: seed, network: .main(.litecoin))
        
        // BIP44 key derivation
        // m/44'
        let purpose = privateKey.derived(at: .hardened(44))
        
        // m/44'/2'
        let coinType = purpose.derived(at: .hardened(2))
        
        // m/44'/0'/0'
        let account = coinType.derived(at: .hardened(0))
        
        // m/44'/0'/0'/0
        let change = account.derived(at: .notHardened(0))
        
        // m/44'/0'/0'/0/0
        
        for i in 0..<2{
            let firstPrivateKey = change.derived(at: .notHardened(UInt32(i)))
            print("Mainnet ChildKey_",i,": ",firstPrivateKey.publicKey.address)
            print("Mainnet PrivateKey_",i,": ",firstPrivateKey.get())
            print("Mainnet PublicKey_",i,": ",firstPrivateKey.publicKey.get())
        }
    }

**change in Class**:

**name: PrivateKey.swift**

1. public func get() -> String {
        switch self.network.coinType {
        case Network.main(.bitcoin).coinType:
            return self.wif()
        
        case Network.test(.bitcoin).coinType:
            return self.wif()
        
        case Network.main(.ethereum).coinType:
            return self.raw.toHexString()
        
        case Network.test(.ethereum).coinType:
            return self.raw.toHexString()
            
        case Network.main(.litecoin).coinType:
            return self.wif()
            
        case Network.test(.litecoin).coinType:
            return self.wif()
         
        case Network.main(.bitcoinCash).coinType:
            return self.wif()
        
        case Network.test(.bitcoinCash).coinType:
            return self.wif()
            
        default:
            return "None"
        }
    }

2. public func wif() -> String {
        if self.network.coinType == Network.main(.bitcoin).coinType {
            var data = Data()
            data += UInt8(0x80)
            data += raw
            data += UInt8(0x01)
            data += data.doubleSHA256.prefix(4)
            return Base58.encode(data)
        }else if self.network.coinType == Network.main(.litecoin).coinType {
            var data = Data()
            data += UInt8(0x80)
            data += raw
            data += UInt8(0x01)
            data += data.doubleSHA256.prefix(4)
            return Base58.encode(data)
        }
        return "WIF is not specified"
    }

if any thing please let me know. Please provide a solution or guide me. I have tried to generate private as per **iancolemean** site.

**Comment by impul** [comment]
@SazzadIproliya, please provide your HDWallet version, and mnemonic that u used in your tests.

**Comment by TBSMobile** [comment]
Hello, I m using 24-word seed.

let mnemonic = "fly weasel genuine enact humor catch prison upper spatial sure mechanic excess hint lazy uphold need violin sport also certain cannon spread include float"
        
let seed = Mnemonic.createSeed(mnemonic: mnemonic)

**Comment by impul** [comment]
@SazzadIproliya I checked your mnemonic and got the same result in HDWallet and Coleman.
```Swift
let mnemonic = "fly weasel genuine enact humor catch prison upper spatial sure mechanic excess hint lazy uphold need violin sport also certain cannon spread include float"
let seed = Mnemonic.createSeed(mnemonic: mnemonic)
let privateKey = PrivateKey(seed: seed, coin: .litecoin)
// BIP44 key derivation
// m/44'
let purpose = privateKey.derived(at: .hardened(44))
// m/44'/2'
let coinType = purpose.derived(at: .hardened(2))
// m/44'/2'/0'
let account = coinType.derived(at: .hardened(0))
// m/44'/2'/0'/0
let change = account.derived(at: .notHardened(0))
// m/44'/2'/0'/0/0
let firstPrivateKey = change.derived(at: .notHardened(0))

let pk = firstPrivateKey.get()
//T4UWHcDKz5hpqbiCwFCoD8ikjZEKxtH1MVHHvSUfbgRjR3WR6JFU
let publicKey = firstPrivateKey.publicKey.get()
//02ddf59d9deb77616c77c8f4c024e0e5137c92c3ad43dd39ad71c8f1e04574110e
let address = firstPrivateKey.publicKey.address
//LXbmmJEuwYrFN21vLGwFkaYz5zeDEDanGv
```
Also I attached screenshots of Coleman:
![screenshot 2018-12-11 at 11 18 55 am](https://user-images.githubusercontent.com/15803807/49790336-9aaeac00-fd36-11e8-9f05-f11b765c5fca.png)
![screenshot 2018-12-11 at 11 18 48 am](https://user-images.githubusercontent.com/15803807/49790337-9aaeac00-fd36-11e8-9385-ed69f4e7d6e5.png)

**Comment by TBSMobile** [comment]
let me check first with the current library. Because in the current project, I have install pod.

Got the solution.
Thanks
