### ISSUE TITLE
How to create bitcoin and litecoin transaction raw with sign?

### ISSUE THREAD

**Issue by TBSMobile** [essentiaone/HDWallet#27]

**Comment by impul** [comment]
Hi, @SazzadIproliya.
This feature is not implemented yet.

**Comment by TBSMobile** [comment]
Hi @impul 
I have a code of the core bitcoin library which I have used for bitcoin wallet. it is working properly. can we use it to create our transaction method?

So we can easily generate transaction raw for this library?

**Comment by impul** [comment]
@SazzadIproliya, now we are working on the Bitcoin-based signing of transactions. This functionality will be added to HDWallet very soon.

**Comment by impul** [comment]
Hi, @SazzadIproliya , we added sign UTXO based tx at 0.2.0
