### ISSUE TITLE
cocoapods not update?

### ISSUE THREAD

**Issue by zhunye** [essentiaone/HDWallet#35]
I use pod 'HDWalletKit',but find that not have Sign UTXO based transaction

**Comment by zhunye** [comment]
And Unlike with source code, thanks

**Comment by impul** [comment]
Hi, @zhunye, version [0.2.6](https://cocoapods.org/pods/HDWalletKit) contains it.
You can see [example of usage](https://github.com/essentiaone/Essentia-iOS/blob/5caf729e8fa2a6f1a5ade4bbce74eeb8413999c0/Modules/dApps/EssWallet/Sources/Controllers/Send/Bitcoin/ConfirmBitcoinTxDetailViewController.swift#L122) in Essentia iOS App

**Comment by impul** [comment]
@zhunye, if something is not clear feel free to reopen the issue.
