### ISSUE TITLE
Private key generation does not work on iPhones having processor make Apple A6

### ISSUE THREAD

**Issue by cbhaiji** [essentiaone/HDWallet#39]
Getting `Fatal error: Operation is not supported ios` error while generating private key:             

**Calling:**
`
privateKey = privateKey.derived(at: .hardened(index))
`

**Crashing at:**
`
 (mulHi, mulLo) = l.multipliedFullWidth(by: multiplicand)
`

I tried to look for the issue and found that the issue is related to the architecture of the processor. The library currently supports 64-bit processors and not 32-bit (A6).

**Comment by impul** [comment]
Hi, @cbhaiji, unfortunately, for now, we do do not support 32-bit architecture. That is a reason that we support iOS 11.0 and higher.
